/* Copyright (C) 2014-2015 by Jacob Alexander
 *
 * This file is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This file is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this file.  If not, see <http://www.gnu.org/licenses/>.
 */

// This file was generated by the kll compiler, DO NOT EDIT.
// Generation Date:    2016-04-06
// KLL Backend:        kiibohd
// KLL Git Rev:        323dd65d4201f753693c86cb25500cfd01d8cf13
// KLL Git Changes:    None
// Compiler arguments:
//    ../../kll/kll.py
//      /Users/nyaray/Code/controller/Scan/MatrixARM/capabilities.kll
//      /Users/nyaray/Code/controller/Macro/PartialMap/capabilities.kll
//      /Users/nyaray/Code/controller/Output/pjrcUSB/capabilities.kll
//      /Users/nyaray/Code/controller/Scan/fekey/defaultMap.kll
//      -d
//      /Users/nyaray/Code/controller/kll/layouts/fekeyOverlay.kll
//      -p
//      /Users/nyaray/Code/controller/kll/layouts/fekeySymbols.kll
//      -p
//      /Users/nyaray/Code/controller/kll/layouts/fekeyFuns.kll
//      -p
//      /Users/nyaray/Code/controller/kll/layouts/fekeyNavigation.kll
//    --backend
//      kiibohd
//    --templates
//      /Users/nyaray/Code/controller/kll/templates/kiibohdKeymap.h
//      /Users/nyaray/Code/controller/kll/templates/kiibohdDefs.h
//    --outputs
//      generatedKeymap.h
//      kll_defs.h
//
// - Base Layer -
//    MatrixArmCapabilities
//      /Users/nyaray/Code/controller/Scan/MatrixARM/capabilities.kll
//    PartialMapCapabilities
//      /Users/nyaray/Code/controller/Macro/PartialMap/capabilities.kll
//    pjrcUSBCapabilities
//      /Users/nyaray/Code/controller/Output/pjrcUSB/capabilities.kll
//    Fekey
//      /Users/nyaray/Code/controller/Scan/fekey/defaultMap.kll
// - Default Layer -
//    fekeyOverlay
//      /Users/nyaray/Code/controller/kll/layouts/fekeyOverlay.kll
// - Partial Layers -
//    Layer 1
//     fekeySymbols
//       /Users/nyaray/Code/controller/kll/layouts/fekeySymbols.kll
//    Layer 2
//     fekeyFuns
//       /Users/nyaray/Code/controller/kll/layouts/fekeyFuns.kll
//    Layer 3
//     fekeyNavigation
//       /Users/nyaray/Code/controller/kll/layouts/fekeyNavigation.kll



#pragma once

// ----- Enums -----

// Capability Indices
typedef enum CapabilityIndex {
	Macro_layerLatch_capability_index,
	Macro_layerLock_capability_index,
	Macro_layerRotate_capability_index,
	Macro_layerShift_capability_index,
	Macro_layerState_capability_index,
	Output_consCtrlSend_capability_index,
	Output_flashMode_capability_index,
	Output_kbdProtocolBoot_capability_index,
	Output_kbdProtocolNKRO_capability_index,
	Output_noneSend_capability_index,
	Output_sysCtrlSend_capability_index,
	Output_usbCodeSend_capability_index,
	Output_usbMouse_capability_index,
} CapabilityIndex;



// ----- KLL Variables -----




// ----- Defines -----

// -- Interconnect Node Maximum --
#define InterconnectNodeMax 0x1



#define USBProtocol_define 1
#define StateWordSize_define 8
#define MinDebounceTime_define 5
#define flashModeEnabled_define 1
#define DebounceThrottleDiv_define 0
#define DebounceDivThreshold_define 65535
#define KeyboardLocale_define 0

